    CREATE TABLE IF NOT EXISTS `#__ucoscan_ucoscansite` (
      `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
      `domain_parent_id` int(10) unsigned NOT NULL,
      `suffix_parent_id` int(10) unsigned NOT NULL,
      `title` varchar(250) NOT NULL DEFAULT '',
      `detecteucoscan` varchar(250) NOT NULL DEFAULT '',
      `alias` varchar(255) NOT NULL DEFAULT '',
      `catid` int(11) NOT NULL DEFAULT '0',
      `state` tinyint(1) NOT NULL default '0',
      `image` varchar(255) NOT NULL,
      `company` varchar(250) NOT NULL DEFAULT '',
      `phone` varchar(12) NOT NULL DEFAULT '',
      `url` varchar(255) NOT NULL,  
      `description` TEXT,
      `publish_up` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
      `publish_down` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
      `ordering` int(11) NOT NULL DEFAULT '0',
      `checked_out` int(11) NOT NULL DEFAULT '0',
      `checked_out_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
      `access` int(11) NOT NULL DEFAULT '1',
      `language` char(7) NOT NULL DEFAULT '',
      `created` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
      `created_by` int(10) unsigned NOT NULL DEFAULT '0',
      `created_by_alias` varchar(255) NOT NULL DEFAULT '',
      `modified` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
      `modified_by` int(10) unsigned NOT NULL DEFAULT '0',
      `metakey` text NOT NULL,
      `metadesc` text NOT NULL,
      `metadata` text NOT NULL,
      `params` text NOT NULL,
      `featured` tinyint(3) unsigned NOT NULL DEFAULT '0',
       PRIMARY KEY (`id`),
       KEY `idx_state` (`state`),
       KEY `idx_domain_parent_id` (`domain_parent_id`),
       KEY `idx_suffix_parent_id` (`suffix_parent_id`),
       KEY `idx_url` (`url`),
       KEY `idx_catid` (`catid`)
    ) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

    CREATE TABLE IF NOT EXISTS `#__ucoscan_domain` (
      `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
      `title` varchar(250) NOT NULL DEFAULT '',
      `alias` varchar(255) NOT NULL DEFAULT '',
      `catid` int(11) NOT NULL DEFAULT '0',
      `state` tinyint(1) NOT NULL default '0',
      `image` varchar(255) NOT NULL,
      `company` varchar(250) NOT NULL DEFAULT '',
      `phone` varchar(12) NOT NULL DEFAULT '',
      `url` varchar(255) NOT NULL,  
      `description` TEXT,
      `publish_up` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
      `publish_down` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
      `ordering` int(11) NOT NULL DEFAULT '0',
      `checked_out` int(11) NOT NULL DEFAULT '0',
      `checked_out_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
      `access` int(11) NOT NULL DEFAULT '1',
      `language` char(7) NOT NULL DEFAULT '',
      `created` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
      `created_by` int(10) unsigned NOT NULL DEFAULT '0',
      `created_by_alias` varchar(255) NOT NULL DEFAULT '',
      `modified` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
      `modified_by` int(10) unsigned NOT NULL DEFAULT '0',
      `metakey` text NOT NULL,
      `metadesc` text NOT NULL,
      `metadata` text NOT NULL,
      `params` text NOT NULL,
      `featured` tinyint(3) unsigned NOT NULL DEFAULT '0',
       PRIMARY KEY (`id`)
           ) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

 CREATE TABLE IF NOT EXISTS `#__ucoscan_suffix` (
      `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
      `title` varchar(250) NOT NULL DEFAULT '',
      `alias` varchar(255) NOT NULL DEFAULT '',
      `catid` int(11) NOT NULL DEFAULT '0',
      `state` tinyint(1) NOT NULL default '0',
      `image` varchar(255) NOT NULL,
      `company` varchar(250) NOT NULL DEFAULT '',
      `phone` varchar(12) NOT NULL DEFAULT '',
      `url` varchar(255) NOT NULL,  
      `description` TEXT,
      `publish_up` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
      `publish_down` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
      `ordering` int(11) NOT NULL DEFAULT '0',
      `checked_out` int(11) NOT NULL DEFAULT '0',
      `checked_out_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
      `access` int(11) NOT NULL DEFAULT '1',
      `language` char(7) NOT NULL DEFAULT '',
      `created` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
      `created_by` int(10) unsigned NOT NULL DEFAULT '0',
      `created_by_alias` varchar(255) NOT NULL DEFAULT '',
      `modified` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
      `modified_by` int(10) unsigned NOT NULL DEFAULT '0',
      `metakey` text NOT NULL,
      `metadesc` text NOT NULL,
      `metadata` text NOT NULL,
      `params` text NOT NULL,
      `featured` tinyint(3) unsigned NOT NULL DEFAULT '0',
       PRIMARY KEY (`id`)
           ) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
